### PR TITLE
Add count method to Query and IQuery

### LINKED ISSUE #56: How to count?
How to get only count of the results by using `getAll` method?

On the one side i want to fetch entity results paged (using skip & take), and on the another side i want to fetch total results without paged (without using skip & take). The entity results are going to be shown for table paged data, and the total results are going to be used on the pagination total count for showing total available pages.

Or maybe there is a feature to clone query (IQuery)?

### PR DESCRIPTION
**Pull request by labibramadhan**
Resolve #56

### CODE REVIEW

**Comment by IRCraziestTaxi** [comment]
Thanks for bringing this up and opening a PR!

As explained in my comment on the linked issue, the implementation I published addresses not only counting but the "reusable query" concern as well, so I'm going to close this PR.

**Comment by IRCraziestTaxi** [comment]
As explained in comment on the linked issue, going to revert my changes when I have time and go with yours instead.

I will go ahead and say: can you put `count` in `Query` and `IQueryBase` in alphabetical order with the other public methods?

**Comment by IRCraziestTaxi** [comment]
@labibramadhan Sorry, should have mentioned you before to make sure you saw my comment, but can you address that comment I made about putting `count` in alphabetical order? Just wanted to make sure you saw it.

**Comment by labibramadhan** [comment]
Done, sorry i thought the order was about functional order, so i put to the most below near non select parts

**Comment by IRCraziestTaxi** [comment]
Perfect, thanks! I'm glad you created this PR - it would have undoubtedly ended up being more complicated than necessary had I had my way with it.

**Pull request merged**
